name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up rye
        uses: zztkm/setup-rye@use-uv
        with:
          use-uv: 'true'
      - name: Install dependencies
        run: rye sync --no-lock
      - name: Run lint
        run: rye run lint
      - name: Run test
        run: rye run test
